import type { SellerStudioState } from "@/lib/seller-studio-types";

export const emptySellerStudioState: SellerStudioState = {
  schemaVersion: 2,
  sellerName: "Seller",
  accountEmail: "",
  accountPendingEmail: "",
  store: {
    id: "",
    slug: "",
    name: "Your Store",
    tagline: "",
    description: "",
    city: "Lusaka",
    area: "",
    categories: [],
    whatsapp: "",
    facebookUrl: "",
    tiktokUrl: "",
    whatsappTone: "standard",
    collectionEnabled: false,
    collectionArea: "",
    collection: "",
    deliveryEnabled: false,
    deliveryScope: "within_city",
    deliveryFeeMode: "whatsapp",
    deliveryFee: undefined,
    delivery: "",
    exchanges: "",
    cancellation: "",
    replyExpectation: "",
    avatarImage: "",
    coverImage: "",
    operatingState: "draft",
    updatedAt: new Date(0).toISOString(),
    version: 1,
  },
  products: [],
  productMetrics: {},
  enquiries: [],
  drops: [],
  notifications: [],
  preferences: {
    enquiryAlerts: true,
    freshnessReminders: true,
    weeklySummary: false,
    compactCatalog: false,
  },
  onboardingStep: 0,
  onboardingComplete: false,
  audit: [],
};
